workflows:
  build-hianime-webview:
    name: Build HiAnime Webview (Final Fix)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        WEBVIEW_URL: "https://hianime.to/home" 
        APP_NAME: "HiAnime"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
        - pattern: 'master'
    scripts:
      - name: Download & Configure Open Source Wrapper
        script: |
          echo "🧹 Clearing current directory..."
          rm -rf * rm -rf .git
          
          echo "⬇️ Cloning Replacement WebView..."
          git clone https://github.com/thejohncotton/ios-webview.git temp_clone
          mv temp_clone/* .
          rm -rf temp_clone

          echo "🔗 Injecting URL..."
          # Replace the default URL with yours
          find . -name "*.swift" -type f -exec sed -i "" "s|https://apple.com|$WEBVIEW_URL|g" {} +

          echo "📱 Renaming App..."
          # Find the Info.plist file automatically
          INFO_PLIST=$(find . -name "Info.plist" -maxdepth 4 | head -n 1)
          
          if [ -n "$INFO_PLIST" ]; then
            echo "Found Info.plist at: $INFO_PLIST"
            
            # LOGIC: Try to SET the name. If it fails (because it doesn't exist), ADD it instead.
            /usr/libexec/PlistBuddy -c "Set :CFBundleName $APP_NAME" "$INFO_PLIST" || /usr/libexec/PlistBuddy -c "Add :CFBundleName string $APP_NAME" "$INFO_PLIST"
            
            # Same logic for Display Name
            /usr/libexec/PlistBuddy -c "Set :CFBundleDisplayName $APP_NAME" "$INFO_PLIST" || /usr/libexec/PlistBuddy -c "Add :CFBundleDisplayName string $APP_NAME" "$INFO_PLIST"
            
            echo "✅ App name updated to $APP_NAME"
          else
            echo "⚠️ Info.plist not found, skipping rename."
          fi

      - name: Build Unsigned .app
        script: |
          # Automatically find the project file
          PROJECT_NAME=$(find . -name "*.xcodeproj" -maxdepth 2 | head -n 1)
          SCHEME_NAME=$(basename "$PROJECT_NAME" .xcodeproj)

          echo "🔨 Building $PROJECT_NAME with scheme $SCHEME_NAME..."

          xcodebuild build \
            -project "$PROJECT_NAME" \
            -scheme "$SCHEME_NAME" \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -derivedDataPath build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Package .app into .ipa
        script: |
          mkdir -p Payload
          cp -r build/Build/Products/Release-iphoneos/*.app Payload/
          zip -r "HiAnime_Unsigned.ipa" Payload

    artifacts:
      - HiAnime_Unsigned.ipa
