workflows:
  build-hianime-webview:
    name: Build HiAnime Webview (Fixed)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        WEBVIEW_URL: "https://hianime.to/home" 
        APP_NAME: "HiAnime"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
        - pattern: 'master'
    scripts:
      - name: Download & Configure Open Source Wrapper
        script: |
          echo "🧹 Clearing current directory..."
          rm -rf * rm -rf .git
          
          echo "⬇️ Cloning Open Source WebView..."
          # Clone into a temp folder first to avoid "Directory not empty" errors
          git clone https://github.com/kemalenver/WebViewApp.git temp_clone
          
          # Move files to current directory and cleanup
          mv temp_clone/* .
          rm -rf temp_clone

          echo "📂 Verifying Files..."
          ls -la # debug: showing files to ensure xcodeproj is here

          echo "🔗 Injecting URL..."
          # Inject your specific URL
          find . -name "ViewController.swift" -type f -exec sed -i "" "s|https://www.google.com|$WEBVIEW_URL|g" {} +

          echo "📱 Renaming App..."
          # Update Info.plist with your app name
          /usr/libexec/PlistBuddy -c "Set :CFBundleName $APP_NAME" WebViewApp/Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleDisplayName $APP_NAME" WebViewApp/Info.plist

      - name: Build Unsigned .app
        script: |
          # We hardcode the names because we know exactly what we cloned
          PROJECT_NAME="WebViewApp.xcodeproj"
          SCHEME_NAME="WebViewApp"

          echo "🔨 Building $PROJECT_NAME with scheme $SCHEME_NAME..."

          xcodebuild build \
            -project "$PROJECT_NAME" \
            -scheme "$SCHEME_NAME" \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -derivedDataPath build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Package .app into .ipa
        script: |
          mkdir -p Payload
          cp -r build/Build/Products/Release-iphoneos/*.app Payload/
          zip -r "HiAnime_Unsigned.ipa" Payload

    artifacts:
      - HiAnime_Unsigned.ipa
