workflows:
  build-hianime-webview:
    name: Build HiAnime Webview (Clean Rewrite)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        WEBVIEW_URL: "https://hianime.to/home" 
        APP_NAME: "HiAnime"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
        - pattern: 'master'
    scripts:
      - name: Download & Configure Open Source Wrapper
        script: |
          echo "🧹 Clearing current directory..."
          # FIX: Explicitly remove the hidden .git folder and all files
          rm -rf .git
          rm -rf *

          echo "⬇️ Cloning Open Source WebView..."
          git clone https://github.com/kemalenver/WebViewApp.git .

          echo "🔗 Injecting URL..."
          # We use 'find' to locate the ViewController file wherever it is
          # This makes the script "crash-proof" even if the folder name changes
          find . -name "ViewController.swift" -type f -exec sed -i "" "s|https://www.google.com|$WEBVIEW_URL|g" {} +

          echo "📱 Renaming App..."
          # We use 'find' to locate the Info.plist file
          INFO_PLIST=$(find . -name "Info.plist" -maxdepth 3 | head -n 1)
          
          if [ -n "$INFO_PLIST" ]; then
            /usr/libexec/PlistBuddy -c "Set :CFBundleName $APP_NAME" "$INFO_PLIST"
            /usr/libexec/PlistBuddy -c "Set :CFBundleDisplayName $APP_NAME" "$INFO_PLIST"
          else
            echo "⚠️ Warning: Info.plist not found. App name might be default."
          fi

      - name: Build Unsigned .app
        script: |
          # Automatically find the project file since we just cloned it
          PROJECT_NAME=$(find . -name "*.xcodeproj" -maxdepth 1 | head -n 1)
          SCHEME_NAME=$(basename "$PROJECT_NAME" .xcodeproj)

          xcodebuild build \
            -project "$PROJECT_NAME" \
            -scheme "$SCHEME_NAME" \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -derivedDataPath build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Package .app into .ipa
        script: |
          mkdir -p Payload
          cp -r build/Build/Products/Release-iphoneos/*.app Payload/
          zip -r "HiAnime_Unsigned.ipa" Payload

    artifacts:
      - HiAnime_Unsigned.ipa
