workflows:
  build-unsigned-ipa:
    name: Build Unsigned IPA
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_SCHEME: "HiAnime"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
        - pattern: 'master'
    scripts:
      - name: Surgical Fix of Podfile & Dependencies
        script: |
          echo "ðŸ› ï¸ Starting Surgical Fixes..."

          # FIX 1: Remove the private "gonative-specs" source link
          sed -i "" "/gonative-specs/d" Podfile || sed -i "/gonative-specs/d" Podfile
          
          # FIX 2: Convert any SSH links to HTTPS
          sed -i "" "s/git@github.com:/https:\/\/github.com\//g" Podfile || sed -i "s/git@github.com:/https:\/\/github.com\//g" Podfile
          
          # FIX 3: DELETE 'MedianIcons' dependency
          sed -i "" "/MedianIcons/d" Podfile || sed -i "/MedianIcons/d" Podfile

          # FIX 4: DELETE 'GoNativeCore' dependency (The private engine)
          sed -i "" "/GoNativeCore/d" Podfile || sed -i "/GoNativeCore/d" Podfile

          # FIX 5: INJECT 'GoNativeIOS' dependency (The public engine)
          # We add this to the end of the Podfile to force it to use the open source version
          echo "pod 'GoNativeIOS', :git => 'https://github.com/gonativeio/gonative-ios.git'" >> Podfile

          # FIX 6: Rename imports in Swift/Obj-C files
          # The app will try to 'import GoNativeCore', we switch it to 'import GoNativeIOS'
          find . -name "*.swift" -type f -exec sed -i "" "s/import GoNativeCore/import GoNativeIOS/g" {} +
          find . -name "*.m" -type f -exec sed -i "" "s/#import <GoNativeCore/#import <GoNativeIOS/g" {} +
          
          # FIX 7: Remove 'import MedianIcons' to prevent crashes
          find . -name "*.swift" -type f -exec sed -i "" "/import MedianIcons/d" {} +
          
          echo "âœ… Fixes applied. Installing Pods..."

          # Install the pods
          pod install --repo-update

      - name: Build Unsigned .app
        script: |
          xcodebuild build \
            -workspace "HiAnime.xcworkspace" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -derivedDataPath build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            ENABLE_USER_SCRIPT_SANDBOXING=NO

      - name: Package .app into .ipa
        script: |
          mkdir -p Payload
          cp -r build/Build/Products/Release-iphoneos/*.app Payload/
          zip -r "HiAnime_Unsigned.ipa" Payload

    artifacts:
      - HiAnime_Unsigned.ipa
