workflows:
  build-unsigned-ipa:
    name: Build Unsigned IPA
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        # 1. We set your exact scheme here
        XCODE_SCHEME: "HiAnime"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
        - pattern: 'master'
    scripts:
      - name: Install CocoaPods (if needed)
        script: |
          # If a Podfile exists, we must install pods or the build will fail.
          if [ -f "Podfile" ]; then
            pod install
          fi

      - name: Build Unsigned .app
        script: |
          # 2. Build command
          # CHECK THIS: If you only have a blue .xcodeproj file and NO white .xcworkspace file,
          # change "-workspace HiAnime.xcworkspace" to "-project HiAnime.xcodeproj"
          
          xcodebuild build \
            -workspace "HiAnime.xcworkspace" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -derivedDataPath build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Package .app into .ipa
        script: |
          mkdir -p Payload
          # We look for the app in the build directory
          cp -r build/Build/Products/Release-iphoneos/*.app Payload/
          zip -r "HiAnime_Unsigned.ipa" Payload

    artifacts:
      - HiAnime_Unsigned.ipa
