workflows:
  build-unsigned-ipa:
    name: Build Unsigned IPA
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_SCHEME: "HiAnime"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
        - pattern: 'master'
    scripts:
      - name: Fix Podfile & Code Dependencies
        script: |
          # FIX 1: Remove the private "gonative-specs" source
          sed -i "" "/gonative-specs/d" Podfile || sed -i "/gonative-specs/d" Podfile
          
          # FIX 2: Convert SSH links to HTTPS
          sed -i "" "s/git@github.com:/https:\/\/github.com\//g" Podfile || sed -i "s/git@github.com:/https:\/\/github.com\//g" Podfile
          
          # FIX 4: Remove the private 'MedianIcons' pod requirement
          # This deletes the line "pod 'MedianIcons'" from the Podfile
          sed -i "" "/MedianIcons/d" Podfile || sed -i "/MedianIcons/d" Podfile

          # FIX 5: Remove "import MedianIcons" from all Swift files
          # This prevents the compiler from crashing because the pod is missing
          find . -name "*.swift" -type f -exec sed -i "" "/import MedianIcons/d" {} +

          # Install the remaining valid pods
          pod install --repo-update

      - name: Build Unsigned .app
        script: |
          # FIX 3: Disable User Script Sandboxing
          xcodebuild build \
            -workspace "HiAnime.xcworkspace" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -derivedDataPath build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            ENABLE_USER_SCRIPT_SANDBOXING=NO

      - name: Package .app into .ipa
        script: |
          mkdir -p Payload
          cp -r build/Build/Products/Release-iphoneos/*.app Payload/
          zip -r "HiAnime_Unsigned.ipa" Payload

    artifacts:
      - HiAnime_Unsigned.ipa
