workflows:
  build-hianime-icon-ready:
    name: Build HiAnime (Icon Ready)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        WEBVIEW_URL: "https://hianime.to/home" 
        APP_NAME: "HiAnime"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
        - pattern: 'master'
    scripts:
      - name: Download & Configure Open Source Wrapper
        script: |
          echo "ðŸ§¹ Clearing directory..."
          rm -rf * rm -rf .git
          
          echo "â¬‡ï¸ Cloning Wrapper..."
          git clone https://github.com/thejohncotton/ios-webview.git temp_clone
          mv temp_clone/* .
          rm -rf temp_clone

          echo "ðŸ”— Injecting URL..."
          find . -name "*.swift" -type f -exec sed -i "" "s|https://apple.com|$WEBVIEW_URL|g" {} +
          find . -name "*.swift" -type f -exec sed -i "" "s|https://www.google.com|$WEBVIEW_URL|g" {} +

          echo "ðŸ“± Renaming App..."
          INFO_PLIST=$(find . -name "Info.plist" -maxdepth 4 | head -n 1)
          if [ -n "$INFO_PLIST" ]; then
            /usr/libexec/PlistBuddy -c "Set :CFBundleName $APP_NAME" "$INFO_PLIST" || /usr/libexec/PlistBuddy -c "Add :CFBundleName string $APP_NAME" "$INFO_PLIST"
            /usr/libexec/PlistBuddy -c "Set :CFBundleDisplayName $APP_NAME" "$INFO_PLIST" || /usr/libexec/PlistBuddy -c "Add :CFBundleDisplayName string $APP_NAME" "$INFO_PLIST"
          fi

          echo "ðŸ“ FIX: Full Screen..."
          VC_FILE=$(find . -name "ViewController.swift" -type f | head -n 1)
          if [ -n "$VC_FILE" ]; then
             sed -i "" '/super.viewDidLoad()/a\
             webView.scrollView.contentInsetAdjustmentBehavior = .never\
             ' "$VC_FILE"
          fi

          echo "ðŸŽ¨ FIX: Creating Icon 'Landing Pad'..."
          # 1. Ensure the Assets folder exists
          mkdir -p WebViewApp/Assets.xcassets/AppIcon.appiconset
          
          # 2. Create a generic placeholder image (using a 1x1 pixel generic image for structure)
          # We just need a file to exist so the signing app can replace it.
          curl -L -o WebViewApp/Assets.xcassets/AppIcon.appiconset/1024.png "https://via.placeholder.com/1024.png/FFFFFF/FFFFFF"

          # 3. Create the configuration file that links the image to iOS
          cat > WebViewApp/Assets.xcassets/AppIcon.appiconset/Contents.json <<EOF
          {
            "images" : [
              { "size" : "1024x1024", "idiom" : "ios-marketing", "filename" : "1024.png", "scale" : "1x" },
              { "size" : "60x60", "idiom" : "iphone", "filename" : "1024.png", "scale" : "2x" },
              { "size" : "60x60", "idiom" : "iphone", "filename" : "1024.png", "scale" : "3x" },
              { "size" : "76x76", "idiom" : "ipad", "filename" : "1024.png", "scale" : "2x" },
              { "size" : "83.5x83.5", "idiom" : "ipad", "filename" : "1024.png", "scale" : "2x" }
            ],
            "info" : { "version" : 1, "author" : "xcode" }
          }
          EOF
          
          # 4. CRITICAL: Tell the app "Hey, look in the Assets folder for the icon"
          # Without this line in Info.plist, the app ignores the images we just downloaded.
          if [ -n "$INFO_PLIST" ]; then
             /usr/libexec/PlistBuddy -c "Delete :CFBundleIconName" "$INFO_PLIST" 2>/dev/null
             /usr/libexec/PlistBuddy -c "Add :CFBundleIconName string AppIcon" "$INFO_PLIST"
             echo "âœ… Info.plist updated to look for AppIcon"
          fi

      - name: Build Unsigned .app
        script: |
          PROJECT_NAME=$(find . -name "*.xcodeproj" -maxdepth 2 | head -n 1)
          SCHEME_NAME=$(basename "$PROJECT_NAME" .xcodeproj)
          xcodebuild build \
            -project "$PROJECT_NAME" \
            -scheme "$SCHEME_NAME" \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -derivedDataPath build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Package .app into .ipa
        script: |
          mkdir -p Payload
          cp -r build/Build/Products/Release-iphoneos/*.app Payload/
          zip -r "HiAnime_IconReady.ipa" Payload

    artifacts:
      - HiAnime_IconReady.ipa
