workflows:
  build-hianime-stable-fix:
    name: Build HiAnime (Compiler Fix)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        WEBVIEW_URL: "https://hianime.to/home" 
        APP_NAME: "HiAnime"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
        - pattern: 'master'
    scripts:
      - name: Download & Configure Wrapper
        script: |
          echo "ðŸ§¹ Clearing directory..."
          rm -rf .git
          rm -rf *
          
          echo "â¬‡ï¸ Cloning Wrapper..."
          git clone https://github.com/thejohncotton/ios-webview.git temp_clone
          mv temp_clone/* .
          rm -rf temp_clone

          echo "ðŸ“± Renaming App..."
          INFO_PLIST=$(find . -name "Info.plist" -maxdepth 4 | head -n 1)
          if [ -n "$INFO_PLIST" ]; then
            /usr/libexec/PlistBuddy -c "Set :CFBundleName $APP_NAME" "$INFO_PLIST" || /usr/libexec/PlistBuddy -c "Add :CFBundleName string $APP_NAME" "$INFO_PLIST"
            /usr/libexec/PlistBuddy -c "Set :CFBundleDisplayName $APP_NAME" "$INFO_PLIST" || /usr/libexec/PlistBuddy -c "Add :CFBundleDisplayName string $APP_NAME" "$INFO_PLIST"
            
            # UNLOCK: Allow Arbitrary Loads (Vital for video servers)
            /usr/libexec/PlistBuddy -c "Add :NSAppTransportSecurity:NSAllowsArbitraryLoads bool true" "$INFO_PLIST" 2>/dev/null
            
            # UNLOCK: Background Audio
            /usr/libexec/PlistBuddy -c "Add :UIBackgroundModes array" "$INFO_PLIST" 2>/dev/null
            /usr/libexec/PlistBuddy -c "Add :UIBackgroundModes:0 string audio" "$INFO_PLIST" 2>/dev/null
          fi

          echo "ðŸŽ¬ FIX: Stable Cinema Engine..."
          VC_FILE=$(find . -name "ViewController.swift" -type f | head -n 1)
          
          # We use 'EOF' (quoted) to prevent the shell from breaking Swift syntax
          cat > "$VC_FILE" <<'EOF'
          import UIKit
          import WebKit
          import AVFoundation

          class ViewController: UIViewController, WKNavigationDelegate, WKUIDelegate {
              
              var webView: WKWebView!

              override func viewDidLoad() {
                  super.viewDidLoad()
                  
                  // 1. CONFIGURATION
                  let webConfiguration = WKWebViewConfiguration()
                  webConfiguration.allowsInlineMediaPlayback = true
                  webConfiguration.mediaTypesRequiringUserActionForPlayback = []
                  webConfiguration.allowsPictureInPictureMediaPlayback = true
                  
                  // 2. INITIALIZE
                  webView = WKWebView(frame: .zero, configuration: webConfiguration)
                  webView.navigationDelegate = self
                  webView.uiDelegate = self
                  
                  // 3. UI TWEAKS (No Bounce, Dark Mode)
                  webView.scrollView.bounces = false
                  webView.scrollView.contentInsetAdjustmentBehavior = .never
                  webView.backgroundColor = .black
                  webView.isOpaque = false
                  
                  view.addSubview(webView)
                  view.backgroundColor = .black
                  webView.translatesAutoresizingMaskIntoConstraints = false
                  
                  // 4. CONSTRAINTS (Pinned to edges)
                  NSLayoutConstraint.activate([
                      webView.leadingAnchor.constraint(equalTo: view.leadingAnchor),
                      webView.trailingAnchor.constraint(equalTo: view.trailingAnchor),
                      webView.topAnchor.constraint(equalTo: view.topAnchor),
                      webView.bottomAnchor.constraint(equalTo: view.bottomAnchor)
                  ])
                  
                  // 5. LOAD URL
                  if let url = URL(string: "REPLACE_ME_URL") {
                      // FIX: Changed 'var' to 'let' to stop compiler warning
                      let request = URLRequest(url: url)
                      
                      // iPad User Agent for Desktop-class video player
                      webView.customUserAgent = "Mozilla/5.0 (iPad; CPU OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1"
                      webView.load(request)
                  }
              }
              
              // 6. SAFE AUDIO ACTIVATION
              override func viewDidAppear(_ animated: Bool) {
                  super.viewDidAppear(animated)
                  
                  // FIX: Simplified syntax to prevent "trailing closure" error
                  DispatchQueue.global().async {
                      do {
                          try AVAudioSession.sharedInstance().setCategory(.playback, mode: .moviePlayback)
                          try AVAudioSession.sharedInstance().setActive(true)
                      } catch {
                          print("Audio Session Failed silently")
                      }
                  }
              }
              
              override var preferredStatusBarStyle: UIStatusBarStyle {
                  return .lightContent
              }
          }
          EOF
          
          # Inject the URL now (Safe substitution)
          sed -i "" "s|REPLACE_ME_URL|$WEBVIEW_URL|g" "$VC_FILE"

          echo "ðŸŽ¨ FIX: Creating Icon 'Landing Pad'..."
          mkdir -p WebViewApp/Assets.xcassets/AppIcon.appiconset
          curl -L -o WebViewApp/Assets.xcassets/AppIcon.appiconset/1024.png "https://via.placeholder.com/1024.png/FFFFFF/FFFFFF"

          cat > WebViewApp/Assets.xcassets/AppIcon.appiconset/Contents.json <<EOF
          {
            "images" : [
              { "size" : "1024x1024", "idiom" : "ios-marketing", "filename" : "1024.png", "scale" : "1x" },
              { "size" : "60x60", "idiom" : "iphone", "filename" : "1024.png", "scale" : "2x" },
              { "size" : "60x60", "idiom" : "iphone", "filename" : "1024.png", "scale" : "3x" },
              { "size" : "76x76", "idiom" : "ipad", "filename" : "1024.png", "scale" : "2x" },
              { "size" : "83.5x83.5", "idiom" : "ipad", "filename" : "1024.png", "scale" : "2x" }
            ],
            "info" : { "version" : 1, "author" : "xcode" }
          }
          EOF
          
          if [ -n "$INFO_PLIST" ]; then
             /usr/libexec/PlistBuddy -c "Delete :CFBundleIconName" "$INFO_PLIST" 2>/dev/null
             /usr/libexec/PlistBuddy -c "Add :CFBundleIconName string AppIcon" "$INFO_PLIST"
          fi

      - name: Build Unsigned .app
        script: |
          PROJECT_NAME=$(find . -name "*.xcodeproj" -maxdepth 2 | head -n 1)
          SCHEME_NAME=$(basename "$PROJECT_NAME" .xcodeproj)
          
          xcodebuild build \
            -project "$PROJECT_NAME" \
            -scheme "$SCHEME_NAME" \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -derivedDataPath build \
            IPHONEOS_DEPLOYMENT_TARGET=15.0 \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Package .app into .ipa
        script: |
          mkdir -p Payload
          cp -r build/Build/Products/Release-iphoneos/*.app Payload/
          zip -r "HiAnime_Stable.ipa" Payload

    artifacts:
      - HiAnime_Stable.ipa
