workflows:
  build-hianime-performance:
    name: Build HiAnime (High Performance)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        WEBVIEW_URL: "https://hianime.to/home" 
        APP_NAME: "HiAnime"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
        - pattern: 'master'
    scripts:
      - name: Download & Configure Wrapper
        script: |
          echo "ðŸ§¹ Clearing directory..."
          rm -rf * rm -rf .git
          
          echo "â¬‡ï¸ Cloning Wrapper..."
          git clone https://github.com/thejohncotton/ios-webview.git temp_clone
          mv temp_clone/* .
          rm -rf temp_clone

          echo "ðŸ“± Renaming App..."
          INFO_PLIST=$(find . -name "Info.plist" -maxdepth 4 | head -n 1)
          if [ -n "$INFO_PLIST" ]; then
            /usr/libexec/PlistBuddy -c "Set :CFBundleName $APP_NAME" "$INFO_PLIST" || /usr/libexec/PlistBuddy -c "Add :CFBundleName string $APP_NAME" "$INFO_PLIST"
            /usr/libexec/PlistBuddy -c "Set :CFBundleDisplayName $APP_NAME" "$INFO_PLIST" || /usr/libexec/PlistBuddy -c "Add :CFBundleDisplayName string $APP_NAME" "$INFO_PLIST"
            
            # CRITICAL: Allow HTTP loads (Arbitrary Loads) so video servers aren't blocked
            /usr/libexec/PlistBuddy -c "Add :NSAppTransportSecurity:NSAllowsArbitraryLoads bool true" "$INFO_PLIST" 2>/dev/null
          fi

          echo "ðŸš€ FIX: The High-Performance Engine..."
          # We locate the ViewController file
          VC_FILE=$(find . -name "ViewController.swift" -type f | head -n 1)
          
          # We overwrite it with the LAG-FREE, VIDEO-ENABLED code
          cat > "$VC_FILE" <<EOF
          import UIKit
          import WebKit

          class ViewController: UIViewController, WKNavigationDelegate, WKUIDelegate {
              
              var webView: WKWebView!

              override func viewDidLoad() {
                  super.viewDidLoad()
                  
                  // 1. HIGH PERFORMANCE CONFIGURATION
                  let webConfiguration = WKWebViewConfiguration()
                  
                  // Fix Video Playback: Allow inline video (no fullscreen force) and auto-play
                  webConfiguration.allowsInlineMediaPlayback = true
                  webConfiguration.mediaTypesRequiringUserActionForPlayback = []
                  
                  // Fix Picture-in-Picture
                  webConfiguration.allowsPictureInPictureMediaPlayback = true
                  
                  // Fix Local Storage/Cookies (Helps with login state and player settings)
                  webConfiguration.processPool = WKProcessPool()
                  webConfiguration.websiteDataStore = WKWebsiteDataStore.default()

                  // 2. Initialize WebView
                  webView = WKWebView(frame: .zero, configuration: webConfiguration)
                  webView.navigationDelegate = self
                  webView.uiDelegate = self
                  
                  // 3. REMOVE LAG: Disable 'Drag' interaction which conflicts with scroll on some sites
                  webView.scrollView.bounces = false 
                  webView.scrollView.contentInsetAdjustmentBehavior = .never
                  
                  // 4. Add to view
                  view.addSubview(webView)
                  webView.translatesAutoresizingMaskIntoConstraints = false
                  
                  // 5. FULL SCREEN CONSTRAINTS
                  NSLayoutConstraint.activate([
                      webView.topAnchor.constraint(equalTo: view.topAnchor),
                      webView.bottomAnchor.constraint(equalTo: view.bottomAnchor),
                      webView.leadingAnchor.constraint(equalTo: view.leadingAnchor),
                      webView.trailingAnchor.constraint(equalTo: view.trailingAnchor)
                  ])
                  
                  // 6. Load the URL with a Custom User Agent
                  // (Tricks the site into thinking it's a real Safari browser, not a 'webview')
                  if let url = URL(string: "$WEBVIEW_URL") {
                      var request = URLRequest(url: url)
                      webView.customUserAgent = "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1"
                      webView.load(request)
                  }
              }
              
              // Light status bar for dark anime backgrounds
              override var preferredStatusBarStyle: UIStatusBarStyle {
                  return .lightContent
              }
          }
          EOF
          
          echo "âœ… High-Performance Engine Injected."

          echo "ðŸŽ¨ FIX: Creating Icon 'Landing Pad'..."
          mkdir -p WebViewApp/Assets.xcassets/AppIcon.appiconset
          curl -L -o WebViewApp/Assets.xcassets/AppIcon.appiconset/1024.png "https://via.placeholder.com/1024.png/FFFFFF/FFFFFF"

          cat > WebViewApp/Assets.xcassets/AppIcon.appiconset/Contents.json <<EOF
          {
            "images" : [
              { "size" : "1024x1024", "idiom" : "ios-marketing", "filename" : "1024.png", "scale" : "1x" },
              { "size" : "60x60", "idiom" : "iphone", "filename" : "1024.png", "scale" : "2x" },
              { "size" : "60x60", "idiom" : "iphone", "filename" : "1024.png", "scale" : "3x" },
              { "size" : "76x76", "idiom" : "ipad", "filename" : "1024.png", "scale" : "2x" },
              { "size" : "83.5x83.5", "idiom" : "ipad", "filename" : "1024.png", "scale" : "2x" }
            ],
            "info" : { "version" : 1, "author" : "xcode" }
          }
          EOF
          
          if [ -n "$INFO_PLIST" ]; then
             /usr/libexec/PlistBuddy -c "Delete :CFBundleIconName" "$INFO_PLIST" 2>/dev/null
             /usr/libexec/PlistBuddy -c "Add :CFBundleIconName string AppIcon" "$INFO_PLIST"
          fi

      - name: Build Unsigned .app
        script: |
          PROJECT_NAME=$(find . -name "*.xcodeproj" -maxdepth 2 | head -n 1)
          SCHEME_NAME=$(basename "$PROJECT_NAME" .xcodeproj)
          xcodebuild build \
            -project "$PROJECT_NAME" \
            -scheme "$SCHEME_NAME" \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -derivedDataPath build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Package .app into .ipa
        script: |
          mkdir -p Payload
          cp -r build/Build/Products/Release-iphoneos/*.app Payload/
          zip -r "HiAnime_HighPerf.ipa" Payload

    artifacts:
      - HiAnime_HighPerf.ipa
