workflows:
  build-hianime-webview:
    name: Build HiAnime Webview (Clean Rewrite)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        # 1. Enter the URL you want the app to open
        WEBVIEW_URL: "https://hianime.to/home" 
        # 2. Enter the name of the app (Appears on home screen)
        APP_NAME: "HiAnime"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
        - pattern: 'master'
    scripts:
      - name: Download & Configure Open Source Wrapper
        script: |
          # 1. Delete the "Locked" Median code from the build folder
          rm -rf * # 2. Clone a free, open-source WebView template
          git clone https://github.com/kemalenver/WebViewApp.git .
          
          # 3. Inject the HiAnime URL into the source code
          # This specific repo stores the URL in 'Constants.swift' or 'ViewController.swift'
          # We use sed to replace the default URL with yours
          sed -i "" "s|https://www.google.com|$WEBVIEW_URL|g" WebViewApp/ViewController.swift || echo "URL Replace tried"
          
          # 4. (Optional) Rename the App Bundle
          # This is a bit hacky but updates the display name in Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleName $APP_NAME" WebViewApp/Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleDisplayName $APP_NAME" WebViewApp/Info.plist

      - name: Build Unsigned .app
        script: |
          # Build the new Open Source project
          xcodebuild build \
            -project "WebViewApp.xcodeproj" \
            -scheme "WebViewApp" \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -derivedDataPath build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Package .app into .ipa
        script: |
          mkdir -p Payload
          cp -r build/Build/Products/Release-iphoneos/*.app Payload/
          zip -r "HiAnime_Unsigned.ipa" Payload

    artifacts:
      - HiAnime_Unsigned.ipa
